import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

type Language = "en" | "sw";

type TranslationValue = string | ((vars?: Record<string, string | number>) => string);

type TranslationMap = Record<string, TranslationValue>;

const translations: Record<Language, TranslationMap> = {
  en: {
    "common.brand": "SAFIRISHA",
    "common.adminDashboard": "Admin Dashboard",
    "common.driverInterface": "Driver Interface",
    "common.trackDelivery": "Track Delivery",
    "common.driverView": "Driver View",
    "common.dispatch": "Dispatch",
    "common.drivers": "Drivers",
    "common.reports": "Reports",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.createDelivery": "Create Delivery",
    "common.completeDelivery": "Complete Delivery",
    "common.markDelivered": "Mark as Delivered",
    "common.markInTransit": "Mark In Transit",
    "common.package": "Package",
    "common.route": "Route",
    "common.pickup": "Pickup",
    "common.dropoff": "Drop-off",
    "common.customerPhone": "Customer Phone",
    "common.receivedBy": "Received By",
    "common.assignedDriver": "Assigned Driver",
    "common.live": "Live",
    "common.today": "Today",
    "common.track": "Track",
    "common.search": "Search",
    "common.pending": "Pending",
    "common.assigned": "Assigned",
    "common.inTransit": "In Transit",
    "common.delivered": "Delivered",
    "controls.language": "Language",
    "controls.appearance": "Appearance",
    "controls.theme": "Theme",
    "controls.english": "English",
    "controls.swahili": "Swahili",
    "controls.light": "Light",
    "controls.dark": "Dark",
    "controls.system": "System",
    "landing.platform": "Delivery Operations Platform",
    "landing.ready": "Ready for Dispatch",
    "landing.heading": "Easy delivery control for your team.",
    "landing.subheading":
      "Create jobs, guide drivers, and let customers track with ease.",
    "landing.metric.activeZones": "Active zones",
    "landing.metric.activeZonesNote": "Across Dar es Salaam",
    "landing.metric.avgDispatch": "Average dispatch",
    "landing.metric.avgDispatchNote": "From creation to assignment",
    "landing.metric.trackingAccess": "Tracking access",
    "landing.metric.trackingAccessNote": "Customer self-service",
    "landing.pillar.dispatch": "Dispatch control",
    "landing.pillar.dispatchCopy": "Create and assign deliveries fast.",
    "landing.pillar.driver": "Driver flow",
    "landing.pillar.driverCopy": "Give riders a simple work list.",
    "landing.pillar.customer": "Customer tracking",
    "landing.pillar.customerCopy": "Let customers track with one code.",
    "landing.snapshot": "Operations Snapshot",
    "landing.queue": "Live dispatch queue",
    "landing.queueActive": "18 active",
    "landing.queueNote": "Most jobs are already moving today.",
    "landing.assignTime": "Avg. assignment time",
    "landing.availableRiders": "Available riders",
    "landing.whyWorks": "Why this layout works",
    "landing.why1": "Fits well on a laptop screen.",
    "landing.why2": "Main buttons are clear and easy to use.",
    "landing.why3": "The same look works across the whole app.",
    "nav.operations": "Operations",
    "nav.driverConsole": "Driver Console",
    "nav.customerTracking": "Customer Tracking",
    "admin.overview": "Dispatch Overview",
    "admin.title": "Control center for today's deliveries",
    "admin.description": "Create jobs, assign riders, and watch live progress.",
    "admin.activeQueue": "Active queue",
    "admin.pendingOrders": "Pending Orders",
    "admin.pendingNote": "Waiting for a driver assignment.",
    "admin.availableDrivers": "Available Drivers",
    "admin.availableDriversNote": "Ready to receive new jobs.",
    "admin.fleetAvailability": "Fleet availability",
    "admin.liveDispatch": "Live Dispatch",
    "admin.deliveryBoard": "Delivery board",
    "admin.emptySelection": "Select a delivery to see details and actions.",
    "admin.noMatch": "No deliveries match the current filter.",
    "quickCreate.label": "Quick Create",
    "quickCreate.title": "New delivery request",
    "quickCreate.subtitle": "Add a job and track it live.",
    "quickCreate.description": "Create new delivery",
    "quickCreate.customerName": "Customer Name",
    "quickCreate.customerPhone": "+255...",
    "quickCreate.pickup": "Pickup Location",
    "quickCreate.dropoff": "Drop-off Location",
    "quickCreate.price": "Price (TZS)",
    "detail.selectedDelivery": "Selected Delivery",
    "detail.assignDriver": "Assign Driver",
    "detail.assignDriverNote": "Pick a free rider for this job.",
    "detail.notifyWhatsapp": "Notify Customer via WhatsApp",
    "driver.summary": "Driver Summary",
    "driver.title": "My deliveries",
    "driver.description": "See active jobs and finish deliveries fast.",
    "driver.activeJobs": "Active Jobs",
    "driver.activeJobsNote": "Jobs still on the road.",
    "driver.completed": "Completed",
    "driver.completedNote": "Jobs finished today.",
    "driver.queue": "Delivery Queue",
    "driver.queueTitle": "Active route list",
    "driver.onShift": "On shift",
    "driver.proof": "Proof of Delivery",
    "driver.photoUpload": "Photo upload",
    "driver.photoUploadNote": "Placeholder for package handoff image.",
    "driver.receiverName": "Receiver Name",
    "driver.receiverPlaceholder": "Name of the person receiving",
    "driver.signature": "Signature pad placeholder",
    "driver.completedDeliveries": "Completed Deliveries",
    "driver.receivedBy": ({ name }) => `Received by: ${name}`,
    "tracking.title": "Follow your package in real time",
    "tracking.description": "Enter your tracking ID to see the latest delivery status.",
    "tracking.alwaysAvailable": "Always Available",
    "tracking.alwaysAvailableNote": "Customers can check status any time.",
    "tracking.liveStatus": "Live Status",
    "tracking.liveStatusNote": "From order creation to final delivery.",
    "tracking.result": "Tracking Result",
    "tracking.statusNote": "Status Note",
    "tracking.awaiting": "Awaiting Search",
    "tracking.enterId": "Enter a tracking ID to begin",
    "tracking.awaitingNote": "Search with a tracking ID to view your delivery.",
    "tracking.notFound": "No delivery found with that tracking ID.",
    "tracking.statusCurrent": "Current delivery status",
    "tracking.statusComplete": "Step completed",
    "tracking.statusPending": "Pending step",
    "tracking.note": ({ status }) => `Your order is currently marked as ${status}.`,
    "notFound.message": "Oops! Page not found",
    "notFound.return": "Return to Home",
  },
  sw: {
    "common.brand": "SAFIRISHA",
    "common.adminDashboard": "Dashibodi ya Usimamizi",
    "common.driverInterface": "Sehemu ya Dereva",
    "common.trackDelivery": "Fuatilia Mzigo",
    "common.driverView": "Mwonekano wa Dereva",
    "common.dispatch": "Ugawaji",
    "common.drivers": "Madereva",
    "common.reports": "Ripoti",
    "common.cancel": "Ghairi",
    "common.close": "Funga",
    "common.createDelivery": "Tengeneza Mzigo",
    "common.completeDelivery": "Kamilisha Uwasilishaji",
    "common.markDelivered": "Weka Imefika",
    "common.markInTransit": "Weka Safarini",
    "common.package": "Kifurushi",
    "common.route": "Njia",
    "common.pickup": "Kuchukua",
    "common.dropoff": "Kuwasilisha",
    "common.customerPhone": "Simu ya Mteja",
    "common.receivedBy": "Amepokea",
    "common.assignedDriver": "Dereva Aliyepangiwa",
    "common.live": "Moja kwa Moja",
    "common.today": "Leo",
    "common.track": "Fuatilia",
    "common.search": "Tafuta",
    "common.pending": "Inasubiri",
    "common.assigned": "Imepangiwa",
    "common.inTransit": "Iko Safarini",
    "common.delivered": "Imewasilishwa",
    "controls.language": "Lugha",
    "controls.appearance": "Mwonekano",
    "controls.theme": "Mandhari",
    "controls.english": "Kiingereza",
    "controls.swahili": "Kiswahili",
    "controls.light": "Nuru",
    "controls.dark": "Giza",
    "controls.system": "Mfumo",
    "landing.platform": "Mfumo wa Uendeshaji wa Usafirishaji",
    "landing.ready": "Tayari kwa Ugawaji",
    "landing.heading": "Rahisi kusimamia usafirishaji wa timu yako.",
    "landing.subheading":
      "Tengeneza kazi, elekeza madereva, na wateja wafuatilie kwa urahisi.",
    "landing.metric.activeZones": "Maeneo hai",
    "landing.metric.activeZonesNote": "Kote Dar es Salaam",
    "landing.metric.avgDispatch": "Wastani wa ugawaji",
    "landing.metric.avgDispatchNote": "Kutoka kuunda hadi kupangiwa",
    "landing.metric.trackingAccess": "Upatikanaji wa ufuatiliaji",
    "landing.metric.trackingAccessNote": "Huduma ya kujifuatilia kwa mteja",
    "landing.pillar.dispatch": "Udhibiti wa ugawaji",
    "landing.pillar.dispatchCopy": "Tengeneza na panga mizigo haraka.",
    "landing.pillar.driver": "Mtiririko wa dereva",
    "landing.pillar.driverCopy": "Wape madereva orodha rahisi ya kazi.",
    "landing.pillar.customer": "Ufuatiliaji wa mteja",
    "landing.pillar.customerCopy": "Wateja wafuatilie kwa namba moja.",
    "landing.snapshot": "Muhtasari wa Uendeshaji",
    "landing.queue": "Foleni ya ugawaji hai",
    "landing.queueActive": "18 hai",
    "landing.queueNote": "Kazi nyingi za leo tayari zinaendelea.",
    "landing.assignTime": "Wastani wa kupanga",
    "landing.availableRiders": "Madereva waliopo",
    "landing.whyWorks": "Kwa nini mpangilio huu unafanya kazi",
    "landing.why1": "Inatoshea vizuri kwenye laptop.",
    "landing.why2": "Vitufe vikuu vinaonekana wazi.",
    "landing.why3": "Muonekano mmoja kwa app yote.",
    "nav.operations": "Uendeshaji",
    "nav.driverConsole": "Kituo cha Dereva",
    "nav.customerTracking": "Ufuatiliaji wa Mteja",
    "admin.overview": "Muhtasari wa Ugawaji",
    "admin.title": "Kituo cha kudhibiti mizigo ya leo",
    "admin.description": "Tengeneza kazi, panga madereva, na fuatilia maendeleo.",
    "admin.activeQueue": "Foleni hai",
    "admin.pendingOrders": "Maagizo Yanayosubiri",
    "admin.pendingNote": "Yanasubiri kupangiwa dereva.",
    "admin.availableDrivers": "Madereva Waliopo",
    "admin.availableDriversNote": "Tayari kupokea kazi mpya.",
    "admin.fleetAvailability": "Upatikanaji wa kikosi",
    "admin.liveDispatch": "Ugawaji Hai",
    "admin.deliveryBoard": "Bodi ya mizigo",
    "admin.emptySelection": "Chagua mzigo kuona maelezo na hatua.",
    "admin.noMatch": "Hakuna mizigo inayolingana na kichujio hiki.",
    "quickCreate.label": "Unda Haraka",
    "quickCreate.title": "Ombi jipya la mzigo",
    "quickCreate.subtitle": "Ongeza kazi na fuatilia hali moja kwa moja.",
    "quickCreate.description": "Tengeneza mzigo mpya",
    "quickCreate.customerName": "Jina la Mteja",
    "quickCreate.customerPhone": "+255...",
    "quickCreate.pickup": "Sehemu ya Kuchukua",
    "quickCreate.dropoff": "Sehemu ya Kuwasilisha",
    "quickCreate.price": "Bei (TZS)",
    "detail.selectedDelivery": "Mzigo Uliochaguliwa",
    "detail.assignDriver": "Panga Dereva",
    "detail.assignDriverNote": "Chagua dereva huru kwa kazi hii.",
    "detail.notifyWhatsapp": "Mjulishe Mteja kwa WhatsApp",
    "driver.summary": "Muhtasari wa Dereva",
    "driver.title": "Mizigo yangu",
    "driver.description": "Ona kazi hai na kamilisha mizigo haraka.",
    "driver.activeJobs": "Kazi Hai",
    "driver.activeJobsNote": "Kazi bado ziko njiani.",
    "driver.completed": "Zilizokamilika",
    "driver.completedNote": "Kazi zilizokamilika leo.",
    "driver.queue": "Foleni ya Mizigo",
    "driver.queueTitle": "Orodha ya njia hai",
    "driver.onShift": "Kazini",
    "driver.proof": "Uthibitisho wa Uwasilishaji",
    "driver.photoUpload": "Pakia picha",
    "driver.photoUploadNote": "Nafasi ya picha ya kukabidhi mzigo.",
    "driver.receiverName": "Jina la Mpokeaji",
    "driver.receiverPlaceholder": "Jina la mtu anayepokea",
    "driver.signature": "Nafasi ya saini",
    "driver.completedDeliveries": "Mizigo Iliyokamilika",
    "driver.receivedBy": ({ name }) => `Amepokea: ${name}`,
    "tracking.title": "Fuatilia kifurushi chako kwa wakati halisi",
    "tracking.description": "Weka namba ya ufuatiliaji kuona hali ya mzigo.",
    "tracking.alwaysAvailable": "Daima Inapatikana",
    "tracking.alwaysAvailableNote": "Wateja wanaweza kuangalia hali muda wowote.",
    "tracking.liveStatus": "Hali Hai",
    "tracking.liveStatusNote": "Kutoka kuundwa hadi kufikishwa.",
    "tracking.result": "Matokeo ya Ufuatiliaji",
    "tracking.statusNote": "Maelezo ya Hali",
    "tracking.awaiting": "Inasubiri Utafutaji",
    "tracking.enterId": "Weka namba ya ufuatiliaji kuanza",
    "tracking.awaitingNote": "Tafuta kwa namba ya ufuatiliaji kuona mzigo wako.",
    "tracking.notFound": "Hakuna mzigo uliopatikana kwa namba hiyo ya ufuatiliaji.",
    "tracking.statusCurrent": "Hii ndiyo hali ya sasa",
    "tracking.statusComplete": "Hatua imekamilika",
    "tracking.statusPending": "Hatua inasubiri",
    "tracking.note": ({ status }) => `Oda yako kwa sasa imewekwa kama ${status}.`,
    "notFound.message": "Samahani! Ukurasa haujapatikana",
    "notFound.return": "Rudi Mwanzo",
  },
};

interface AppPreferencesContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const AppPreferencesContext = createContext<AppPreferencesContextValue | null>(null);

export function AppPreferencesProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const stored = window.localStorage.getItem("app-language");
    return stored === "sw" ? "sw" : "en";
  });

  useEffect(() => {
    window.localStorage.setItem("app-language", language);
    document.documentElement.lang = language === "sw" ? "sw" : "en";
  }, [language]);

  const value = useMemo<AppPreferencesContextValue>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((prev) => (prev === "en" ? "sw" : "en")),
      t: (key, vars) => {
        const entry = translations[language][key] ?? translations.en[key] ?? key;
        if (typeof entry === "function") {
          return entry(vars);
        }
        if (!vars) return entry;
        return Object.entries(vars).reduce(
          (acc, [varKey, varValue]) => acc.replace(new RegExp(`{${varKey}}`, "g"), String(varValue)),
          entry
        );
      },
    }),
    [language]
  );

  return <AppPreferencesContext.Provider value={value}>{children}</AppPreferencesContext.Provider>;
}

export function useAppPreferences() {
  const context = useContext(AppPreferencesContext);
  if (!context) {
    throw new Error("useAppPreferences must be used within AppPreferencesProvider");
  }
  return context;
}
